/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Регистрация нового пользователя */
        post: operations["AuthController_signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход в систему */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Запрос на сброс пароля */
        post: operations["AuthController_forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/local": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход через локальную стратегию */
        post: operations["AuthController_loginLocal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обновление токенов */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выход из системы */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить текущего пользователя */
        get: operations["UsersController_getMe"];
        /** Обновить данные текущего пользователя */
        put: operations["UsersController_updateMe"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Обновить профиль текущего пользователя */
        put: operations["UsersController_updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{handle}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить публичный профиль по handle */
        get: operations["UsersController_getPublicProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить все резюме текущего пользователя */
        get: operations["ResumesController_findAll"];
        put?: never;
        /** Создать новое резюме */
        post: operations["ResumesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить резюме по ID */
        get: operations["ResumesController_findOne"];
        /** Обновить резюме */
        put: operations["ResumesController_update"];
        post?: never;
        /** Удалить резюме */
        delete: operations["ResumesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать новую версию резюме */
        post: operations["ResumesController_createVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Опубликовать резюме */
        post: operations["ResumesController_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/{id}/export/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Экспортировать резюме в PDF */
        get: operations["ResumesController_exportPdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/public/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить публичное резюме по slug */
        get: operations["ResumesController_getPublicResume"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить все проекты текущего пользователя */
        get: operations["ProjectsController_findAll"];
        put?: never;
        /** Создать новый проект */
        post: operations["ProjectsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить проект по ID */
        get: operations["ProjectsController_findOne"];
        /** Обновить проект */
        put: operations["ProjectsController_update"];
        post?: never;
        /** Удалить проект */
        delete: operations["ProjectsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить медиа файл к проекту */
        post: operations["ProjectsController_addMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/media/{mediaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить медиа файл из проекта */
        delete: operations["ProjectsController_removeMedia"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/ai/describe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Сгенерировать описание проекта с помощью AI */
        post: operations["ProjectsController_generateDescription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/improve-text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Улучшить текст с помощью AI */
        post: operations["AiController_improveText"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/cover-letter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Сгенерировать сопроводительное письмо с помощью AI */
        post: operations["AiController_generateCoverLetter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/analyze-vs-job": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Проанализировать резюме относительно описания вакансии */
        post: operations["AiController_analyzeVsJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить все достижения текущего пользователя */
        get: operations["AchievementsController_findAll"];
        put?: never;
        /** Создать новое достижение */
        post: operations["AchievementsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/achievements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить достижение по ID */
        get: operations["AchievementsController_findOne"];
        /** Обновить достижение */
        put: operations["AchievementsController_update"];
        post?: never;
        /** Удалить достижение */
        delete: operations["AchievementsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/presigned-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Получить presigned URL для загрузки файла */
        post: operations["StorageController_generatePresignedUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/presigned-download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Получить presigned URL для скачивания файла */
        post: operations["StorageController_generatePresignedDownloadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Загрузить файл напрямую в хранилище */
        post: operations["StorageController_uploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SignupDto: {
            /**
             * @description Email пользователя
             * @example user@example.com
             */
            email: string;
            /**
             * @description Пароль пользователя (минимум 8 символов)
             * @example password123
             */
            password: string;
            /**
             * @description Имя пользователя
             * @example Иван Иванов
             */
            name?: string;
        };
        UserResponseDto: {
            /**
             * @description ID пользователя
             * @example clx1234567890
             */
            id: string;
            /**
             * @description Email пользователя
             * @example user@example.com
             */
            email: string;
            /**
             * @description Подтвержден ли email
             * @example false
             */
            emailVerified: boolean;
            /** @description Имя пользователя */
            name?: Record<string, never> | null;
            /** @description Заголовок профиля */
            headline?: Record<string, never> | null;
            /** @description URL аватара */
            avatarUrl?: Record<string, never> | null;
            /** @description Публичный handle */
            publicHandle?: Record<string, never> | null;
            /**
             * @description Локаль
             * @example en
             */
            locale?: Record<string, never> | null;
            /** @description Профили пользователя */
            profiles?: components["schemas"]["ProfileResponseDto"][];
            /** @description Количество элементов */
            _count?: components["schemas"]["UserCountsDto"];
            /**
             * Format: date-time
             * @description Дата создания
             * @example 2025-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Дата обновления
             * @example 2025-01-01T00:00:00.000Z
             */
            updatedAt: string;
        };
        SignupResponseDto: {
            /** @description Данные пользователя */
            user: components["schemas"]["UserResponseDto"];
        };
        LoginDto: {
            /**
             * @description Email пользователя
             * @example user@example.com
             */
            email: string;
            /**
             * @description Пароль пользователя
             * @example password123
             */
            password: string;
        };
        LoginResponseDto: {
            /** @description Данные пользователя */
            user: components["schemas"]["UserResponseDto"];
        };
        ForgotPasswordDto: {
            /**
             * @description Email пользователя для сброса пароля
             * @example user@example.com
             */
            email: string;
        };
        ForgotPasswordResponseDto: {
            /**
             * @description Сообщение о статусе запроса
             * @example If user exists, password reset email sent
             */
            message: string;
        };
        RefreshResponseDto: {
            /** @description Данные пользователя */
            user: components["schemas"]["UserResponseDto"];
        };
        LogoutResponseDto: {
            /**
             * @description Сообщение об успешном выходе
             * @example Logged out successfully
             */
            message: string;
        };
        LinkResponseDto: {
            /**
             * @description ID ссылки
             * @example clx1234567890
             */
            id: string;
            /**
             * @description URL ссылки
             * @example https://github.com/user
             */
            url: string;
            /**
             * @description Название ссылки
             * @example GitHub
             */
            title?: Record<string, never> | null;
            /**
             * Format: date-time
             * @description Дата создания
             * @example 2025-01-01T00:00:00.000Z
             */
            createdAt: string;
        };
        ProfileResponseDto: {
            /**
             * @description ID профиля
             * @example clx1234567890
             */
            id: string;
            /**
             * @description ID пользователя
             * @example clx1234567890
             */
            userId: string;
            /** @description Биография */
            bio?: Record<string, never> | null;
            /**
             * @description Видимость профиля
             * @example true
             */
            visible: boolean;
            /** @description Ссылки профиля */
            links?: components["schemas"]["LinkResponseDto"][];
            /**
             * Format: date-time
             * @description Дата создания
             * @example 2025-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Дата обновления
             * @example 2025-01-01T00:00:00.000Z
             */
            updatedAt: string;
        };
        UserCountsDto: {
            /**
             * @description Количество резюме
             * @example 3
             */
            resumes: number;
            /**
             * @description Количество проектов
             * @example 5
             */
            projects: number;
            /**
             * @description Количество достижений
             * @example 2
             */
            achievements: number;
        };
        UpdateUserDto: {
            /**
             * @description Имя пользователя
             * @example Иван Иванов
             */
            name?: string;
            /**
             * @description Заголовок профиля
             * @example Senior Full Stack Developer
             */
            headline?: string;
            /**
             * @description URL аватара пользователя
             * @example https://example.com/avatar.jpg
             */
            avatarUrl?: string;
            /**
             * @description Локаль пользователя
             * @example ru-RU
             */
            locale?: string;
            /**
             * @description Публичный handle пользователя
             * @example ivan_ivanov
             */
            publicHandle?: string;
        };
        UpdateProfileDto: {
            /**
             * @description Биография пользователя
             * @example Опытный разработчик с 5+ годами опыта
             */
            bio?: string;
            /**
             * @description Видимость профиля
             * @example true
             */
            visible?: boolean;
        };
        PublicProfileResponseDto: {
            /**
             * @description ID пользователя
             * @example clx1234567890
             */
            id: string;
            /** @description Имя пользователя */
            name?: Record<string, never> | null;
            /** @description Заголовок профиля */
            headline?: Record<string, never> | null;
            /** @description URL аватара */
            avatarUrl?: Record<string, never> | null;
            /** @description Публичный handle */
            publicHandle?: Record<string, never> | null;
            /**
             * @description Локаль
             * @example en
             */
            locale?: Record<string, never> | null;
            /** @description Профили пользователя */
            profiles?: components["schemas"]["ProfileResponseDto"][];
            /** @description Опубликованные резюме */
            resumes?: unknown[];
            /** @description Публичные проекты */
            projects?: unknown[];
            /** @description Достижения */
            achievements?: unknown[];
            /**
             * Format: date-time
             * @description Дата создания
             * @example 2025-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Дата обновления
             * @example 2025-01-01T00:00:00.000Z
             */
            updatedAt: string;
        };
        ResumeVersionResponseDto: {
            /**
             * @description ID версии резюме
             * @example clx1234567890
             */
            id: string;
            /**
             * @description ID резюме
             * @example clx1234567890
             */
            resumeId: string;
            /**
             * @description Содержимое резюме
             * @example {"sections": [...]}
             */
            content: string;
            /**
             * @description Тег версии
             * @example v1.0
             */
            versionTag?: Record<string, never> | null;
            /** @description AI оценка */
            aiScore?: Record<string, never> | null;
            /**
             * Format: date-time
             * @description Дата создания
             * @example 2025-01-01T00:00:00.000Z
             */
            createdAt: string;
        };
        ResumeCountsDto: {
            /**
             * @description Количество версий
             * @example 3
             */
            versions: number;
        };
        ResumeResponseDto: {
            /**
             * @description ID резюме
             * @example clx1234567890
             */
            id: string;
            /**
             * @description ID пользователя
             * @example clx1234567890
             */
            userId: string;
            /**
             * @description Название резюме
             * @example Software Engineer Resume
             */
            title: string;
            /**
             * @description Slug резюме
             * @example software-engineer-resume
             */
            slug: string;
            /** @description Описание резюме */
            description?: Record<string, never> | null;
            /**
             * @description Опубликовано ли резюме
             * @example false
             */
            isPublished: boolean;
            /** @description Версии резюме */
            versions?: components["schemas"]["ResumeVersionResponseDto"][];
            /** @description Количество версий */
            _count?: components["schemas"]["ResumeCountsDto"];
            /**
             * Format: date-time
             * @description Дата создания
             * @example 2025-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Дата обновления
             * @example 2025-01-01T00:00:00.000Z
             */
            updatedAt: string;
        };
        CreateResumeDto: {
            /**
             * @description Название резюме
             * @example Frontend Developer Resume
             */
            title: string;
            /**
             * @description Slug резюме (автоматически генерируется из названия, если не указан)
             * @example frontend-developer-resume
             */
            slug?: string;
            /**
             * @description Описание резюме
             * @example Резюме для позиции Frontend Developer
             */
            description?: string;
        };
        UpdateResumeDto: {
            /**
             * @description Название резюме
             * @example Frontend Developer Resume
             */
            title?: string;
            /**
             * @description Описание резюме
             * @example Резюме для позиции Frontend Developer
             */
            description?: string;
            /**
             * @description Статус публикации резюме
             * @example true
             */
            isPublished?: boolean;
        };
        CreateResumeVersionDto: {
            /**
             * @description Содержимое резюме (markdown или JSON)
             * @example # Experience
             *
             *     ## Company Name
             *     - Developed...
             */
            content: string;
            /**
             * @description Тег версии
             * @example v1.0
             */
            versionTag?: string;
        };
        PublicResumeUserDto: {
            /**
             * @description ID пользователя
             * @example clx1234567890
             */
            id: string;
            /** @description Имя пользователя */
            name?: Record<string, never> | null;
            /** @description Заголовок профиля */
            headline?: Record<string, never> | null;
            /** @description URL аватара */
            avatarUrl?: Record<string, never> | null;
            /** @description Публичный handle */
            publicHandle?: Record<string, never> | null;
        };
        PublicResumeResponseDto: {
            /**
             * @description ID резюме
             * @example clx1234567890
             */
            id: string;
            /**
             * @description ID пользователя
             * @example clx1234567890
             */
            userId: string;
            /**
             * @description Название резюме
             * @example Software Engineer Resume
             */
            title: string;
            /**
             * @description Slug резюме
             * @example software-engineer-resume
             */
            slug: string;
            /** @description Описание резюме */
            description?: Record<string, never> | null;
            /**
             * @description Опубликовано ли резюме
             * @example true
             */
            isPublished: boolean;
            /** @description Данные пользователя */
            user: components["schemas"]["PublicResumeUserDto"];
            /** @description Версии резюме */
            versions: components["schemas"]["ResumeVersionResponseDto"][];
            /**
             * Format: date-time
             * @description Дата создания
             * @example 2025-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Дата обновления
             * @example 2025-01-01T00:00:00.000Z
             */
            updatedAt: string;
        };
        ProjectMediaResponseDto: {
            /**
             * @description ID медиа файла
             * @example clx1234567890
             */
            id: string;
            /**
             * @description ID проекта
             * @example clx1234567890
             */
            projectId: string;
            /**
             * @description URL медиа файла
             * @example https://example.com/image.jpg
             */
            url: string;
            /**
             * @description Тип медиа файла
             * @example IMAGE
             * @enum {string}
             */
            type: "IMAGE" | "VIDEO" | "FILE";
            /** @description Альтернативный текст */
            altText?: Record<string, never> | null;
            /**
             * Format: date-time
             * @description Дата создания
             * @example 2025-01-01T00:00:00.000Z
             */
            createdAt: string;
        };
        ProjectLinkResponseDto: {
            /**
             * @description ID ссылки
             * @example clx1234567890
             */
            id: string;
            /**
             * @description URL ссылки
             * @example https://github.com/user/project
             */
            url: string;
            /**
             * @description Название ссылки
             * @example GitHub Repository
             */
            title?: Record<string, never> | null;
            /**
             * @description ID проекта
             * @example clx1234567890
             */
            projectId?: Record<string, never> | null;
            /**
             * Format: date-time
             * @description Дата создания
             * @example 2025-01-01T00:00:00.000Z
             */
            createdAt: string;
        };
        ProjectCountsDto: {
            /**
             * @description Количество медиа файлов
             * @example 3
             */
            media: number;
            /**
             * @description Количество ссылок
             * @example 2
             */
            links: number;
        };
        ProjectResponseDto: {
            /**
             * @description ID проекта
             * @example clx1234567890
             */
            id: string;
            /**
             * @description ID пользователя
             * @example clx1234567890
             */
            userId: string;
            /**
             * @description Название проекта
             * @example E-commerce Platform
             */
            title: string;
            /**
             * @description Slug проекта
             * @example e-commerce-platform
             */
            slug: string;
            /** @description Краткое описание */
            shortDesc?: Record<string, never> | null;
            /** @description Полное описание */
            description?: Record<string, never> | null;
            /**
             * @description Технологический стек
             * @example [
             *       "React",
             *       "Node.js",
             *       "PostgreSQL"
             *     ]
             */
            techStack: string[];
            /**
             * @description Видимость проекта
             * @example PUBLIC
             * @enum {string}
             */
            visibility: "PUBLIC" | "PRIVATE" | "UNLISTED";
            /** @description Медиа файлы проекта */
            media?: components["schemas"]["ProjectMediaResponseDto"][];
            /** @description Ссылки проекта */
            links?: components["schemas"]["ProjectLinkResponseDto"][];
            /** @description Количество элементов */
            _count?: components["schemas"]["ProjectCountsDto"];
            /**
             * Format: date-time
             * @description Дата создания
             * @example 2025-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Дата обновления
             * @example 2025-01-01T00:00:00.000Z
             */
            updatedAt: string;
        };
        CreateProjectDto: {
            /**
             * @description Название проекта
             * @example E-commerce Platform
             */
            title: string;
            /**
             * @description Slug проекта (автоматически генерируется из названия, если не указан)
             * @example e-commerce-platform
             */
            slug?: string;
            /**
             * @description Краткое описание проекта
             * @example Современная платформа для электронной коммерции
             */
            shortDesc?: string;
            /**
             * @description Полное описание проекта
             * @example Полнофункциональная платформа для электронной коммерции с поддержкой множества платежных систем
             */
            description?: string;
            /**
             * @description Технологический стек проекта
             * @example [
             *       "React",
             *       "Node.js",
             *       "PostgreSQL"
             *     ]
             */
            techStack?: string[];
        };
        UpdateProjectDto: {
            /**
             * @description Название проекта
             * @example E-commerce Platform
             */
            title?: string;
            /**
             * @description Краткое описание проекта
             * @example Современная платформа для электронной коммерции
             */
            shortDesc?: string;
            /**
             * @description Полное описание проекта
             * @example Полнофункциональная платформа для электронной коммерции
             */
            description?: string;
            /**
             * @description Технологический стек проекта
             * @example [
             *       "React",
             *       "Node.js",
             *       "PostgreSQL"
             *     ]
             */
            techStack?: string[];
            /**
             * @description Видимость проекта
             * @example PUBLIC
             * @enum {string}
             */
            visibility?: "PUBLIC" | "PRIVATE" | "UNLISTED";
        };
        ImproveTextDto: {
            /**
             * @description Текст для улучшения
             * @example Я разработал приложение
             */
            text: string;
            /**
             * @description Цель улучшения текста
             * @example Сделать текст более профессиональным
             */
            goal?: string;
            /**
             * @description Язык текста
             * @example ru
             */
            language?: string;
        };
        ImproveTextResponseDto: {
            /**
             * @description Улучшенный текст
             * @example Разработал и внедрил систему, которая увеличила производительность на 40%
             */
            improvedText: string;
        };
        CoverLetterDto: {
            /**
             * @description ID резюме
             * @example clx1234567890
             */
            resumeId: string;
            /**
             * @description Описание вакансии
             * @example Ищем опытного разработчика с опытом работы...
             */
            jobDescription: string;
        };
        CoverLetterResponseDto: {
            /**
             * @description Сгенерированное сопроводительное письмо
             * @example Уважаемый [Имя],
             *
             *     Я пишу, чтобы выразить заинтересованность...
             */
            coverLetter: string;
        };
        AnalyzeVsJobDto: {
            /**
             * @description Текст резюме
             * @example Опытный разработчик с 5+ годами опыта...
             */
            resumeText: string;
            /**
             * @description Описание вакансии
             * @example Ищем опытного разработчика с опытом работы...
             */
            jobDescription: string;
        };
        AnalyzeVsJobResponseDto: {
            /**
             * @description Оценка совместимости резюме с вакансией (от 0 до 1)
             * @example 0.75
             */
            score: number;
            /**
             * @description Предложения по улучшению резюме
             * @example [
             *       "Добавьте больше информации о опыте работы с React",
             *       "Укажите конкретные метрики достижений"
             *     ]
             */
            suggestions: string[];
            /**
             * @description Сильные стороны резюме
             * @example [
             *       "Отличный опыт работы с Node.js",
             *       "Сильные навыки работы в команде"
             *     ]
             */
            strengths: string[];
            /**
             * @description Отсутствующие ключевые слова
             * @example [
             *       "TypeScript",
             *       "Docker",
             *       "Kubernetes"
             *     ]
             */
            missingKeywords: string[];
        };
        AchievementResponseDto: {
            /**
             * @description ID достижения
             * @example clx1234567890
             */
            id: string;
            /**
             * @description ID пользователя
             * @example clx1234567890
             */
            userId: string;
            /**
             * @description Название достижения
             * @example Победитель хакатона
             */
            title: string;
            /** @description Описание достижения */
            body?: Record<string, never> | null;
            /**
             * @description Дата достижения
             * @example 2025-01-01T00:00:00.000Z
             */
            date?: Record<string, never> | null;
            /**
             * @description Ссылка на достижение
             * @example https://example.com/achievement
             */
            link?: Record<string, never> | null;
            /**
             * Format: date-time
             * @description Дата создания
             * @example 2025-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Дата обновления
             * @example 2025-01-01T00:00:00.000Z
             */
            updatedAt: string;
        };
        CreateAchievementDto: {
            /**
             * @description Название достижения
             * @example Победитель хакатона 2024
             */
            title: string;
            /**
             * @description Описание достижения
             * @example Занял первое место на хакатоне по разработке мобильных приложений
             */
            body?: string;
            /**
             * @description Дата достижения
             * @example 2025-01-15
             */
            date?: string;
            /**
             * @description Ссылка на достижение
             * @example https://example.com/achievement
             */
            link?: string;
        };
        UpdateAchievementDto: {
            /**
             * @description Название достижения
             * @example Победитель хакатона 2024
             */
            title?: string;
            /**
             * @description Описание достижения
             * @example Занял первое место на хакатоне по разработке мобильных приложений
             */
            body?: string;
            /**
             * @description Дата достижения
             * @example 2025-01-15
             */
            date?: string;
            /**
             * @description Ссылка на достижение
             * @example https://example.com/achievement
             */
            link?: string;
        };
        PresignedUploadResponseDto: {
            /**
             * @description Presigned URL для загрузки файла
             * @example https://s3.example.com/bucket/file?X-Amz-Algorithm=...
             */
            uploadUrl: string;
            /**
             * @description Ключ файла в хранилище
             * @example uploads/123e4567-e89b-12d3-a456-426614174000.jpg
             */
            fileKey: string;
            /**
             * @description Публичный URL файла
             * @example https://storage.example.com/bucket/uploads/123e4567-e89b-12d3-a456-426614174000.jpg
             */
            publicUrl: string;
        };
        PresignedDownloadResponseDto: {
            /**
             * @description Presigned URL для скачивания файла
             * @example https://s3.example.com/bucket/file?X-Amz-Algorithm=...
             */
            downloadUrl: string;
        };
        UploadFileDto: {
            /**
             * Format: binary
             * @description Файл для загрузки
             */
            file: string;
            /**
             * @description Папка для сохранения файла (опционально)
             * @example uploads
             */
            folder?: string;
        };
        UploadFileResponseDto: {
            /**
             * @description Ключ файла в хранилище
             * @example uploads/123e4567-e89b-12d3-a456-426614174000.jpg
             */
            fileKey: string;
            /**
             * @description Публичный URL файла
             * @example https://storage.example.com/bucket/uploads/123e4567-e89b-12d3-a456-426614174000.jpg
             */
            publicUrl: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupDto"];
            };
        };
        responses: {
            /** @description Пользователь успешно зарегистрирован */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignupResponseDto"];
                };
            };
            /** @description Пользователь с таким email уже существует */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Успешный вход */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            /** @description Неверные учетные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordDto"];
            };
        };
        responses: {
            /** @description Если пользователь существует, отправлено письмо для сброса пароля */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForgotPasswordResponseDto"];
                };
            };
        };
    };
    AuthController_loginLocal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный вход */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Токены успешно обновлены */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponseDto"];
                };
            };
            /** @description Неверный или истекший refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный выход */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponseDto"];
                };
            };
        };
    };
    UsersController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Информация о текущем пользователе */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Пользователь не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            /** @description Данные пользователя обновлены */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Public handle уже занят */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            /** @description Профиль обновлен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponseDto"];
                };
            };
        };
    };
    UsersController_getPublicProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Публичный handle пользователя */
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Публичный профиль пользователя */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProfileResponseDto"];
                };
            };
            /** @description Пользователь не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResumesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список резюме */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponseDto"][];
                };
            };
        };
    };
    ResumesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateResumeDto"];
            };
        };
        responses: {
            /** @description Резюме успешно создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponseDto"];
                };
            };
            /** @description Slug уже занят */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResumesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID резюме */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Информация о резюме */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponseDto"];
                };
            };
            /** @description Доступ запрещен */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Резюме не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResumesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID резюме */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateResumeDto"];
            };
        };
        responses: {
            /** @description Резюме обновлено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponseDto"];
                };
            };
            /** @description Доступ запрещен */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Резюме не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResumesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID резюме */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Резюме удалено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponseDto"];
                };
            };
            /** @description Доступ запрещен */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Резюме не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResumesController_createVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID резюме */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateResumeVersionDto"];
            };
        };
        responses: {
            /** @description Версия резюме создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeVersionResponseDto"];
                };
            };
            /** @description Доступ запрещен */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Резюме не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResumesController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID резюме */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Резюме опубликовано */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponseDto"];
                };
            };
            /** @description Доступ запрещен */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Резюме не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Невозможно опубликовать резюме без версий */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResumesController_exportPdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID резюме */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF файл резюме */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Доступ запрещен */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Резюме не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResumesController_getPublicResume: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug резюме */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Публичное резюме */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicResumeResponseDto"];
                };
            };
            /** @description Резюме не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список проектов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponseDto"][];
                };
            };
        };
    };
    ProjectsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectDto"];
            };
        };
        responses: {
            /** @description Проект успешно создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponseDto"];
                };
            };
            /** @description Slug уже занят */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID проекта */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Информация о проекте */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponseDto"];
                };
            };
            /** @description Доступ запрещен */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Проект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID проекта */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectDto"];
            };
        };
        responses: {
            /** @description Проект обновлен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponseDto"];
                };
            };
            /** @description Доступ запрещен */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Проект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID проекта */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Проект удален */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponseDto"];
                };
            };
            /** @description Доступ запрещен */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Проект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_addMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID проекта */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Медиа файл добавлен */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMediaResponseDto"];
                };
            };
            /** @description Доступ запрещен */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Проект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_removeMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID проекта */
                id: string;
                /** @description ID медиа файла */
                mediaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Медиа файл удален */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMediaResponseDto"];
                };
            };
            /** @description Доступ запрещен */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Проект или медиа файл не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_generateDescription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID проекта */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Описание проекта сгенерировано */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Современная платформа для электронной коммерции... */
                        description?: string;
                    };
                };
            };
            /** @description Доступ запрещен */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Проект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AiController_improveText: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImproveTextDto"];
            };
        };
        responses: {
            /** @description Текст улучшен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImproveTextResponseDto"];
                };
            };
        };
    };
    AiController_generateCoverLetter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoverLetterDto"];
            };
        };
        responses: {
            /** @description Сопроводительное письмо сгенерировано */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverLetterResponseDto"];
                };
            };
        };
    };
    AiController_analyzeVsJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeVsJobDto"];
            };
        };
        responses: {
            /** @description Анализ выполнен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeVsJobResponseDto"];
                };
            };
        };
    };
    AchievementsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список достижений */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AchievementResponseDto"][];
                };
            };
        };
    };
    AchievementsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAchievementDto"];
            };
        };
        responses: {
            /** @description Достижение успешно создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AchievementResponseDto"];
                };
            };
        };
    };
    AchievementsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID достижения */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Информация о достижении */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AchievementResponseDto"];
                };
            };
            /** @description Доступ запрещен */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Достижение не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AchievementsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID достижения */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAchievementDto"];
            };
        };
        responses: {
            /** @description Достижение обновлено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AchievementResponseDto"];
                };
            };
            /** @description Доступ запрещен */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Достижение не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AchievementsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID достижения */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Достижение удалено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AchievementResponseDto"];
                };
            };
            /** @description Доступ запрещен */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Достижение не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StorageController_generatePresignedUploadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Presigned URL для загрузки сгенерирован */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignedUploadResponseDto"];
                };
            };
        };
    };
    StorageController_generatePresignedDownloadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Presigned URL для скачивания сгенерирован */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignedDownloadResponseDto"];
                };
            };
        };
    };
    StorageController_uploadFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Файл для загрузки */
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["UploadFileDto"];
            };
        };
        responses: {
            /** @description Файл успешно загружен */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadFileResponseDto"];
                };
            };
        };
    };
}
